spring.application.name=productos-categorias
# Thymeleaf (para desarrollo)
spring.thymeleaf.cache=false

<!-- Source: https://mvnrepository.com/artifact/com.h2database/h2 -->
<dependency>
<groupId>com.h2database</groupId>
<artifactId>h2</artifactId>
<version>2.4.240</version>
<scope>test</scope>
</dependency>